setuid=pdns
setgid=pdns
local-address=0.0.0.0
local-port=5300
launch=bind
bind-config=/etc/powerdns/named.conf

api=yes
api-key=change-me-before-production
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0

guardian=no
disable-syslog=yes
version-string=anonymous
default-soa-content=ns1.portfolio.test hostmaster.portfolio.test 0 10800 3600 604800 3600
loglevel=6

